### ISSUE TITLE
Any idea how to open Google Services Json GPG file

### ISSUE THREAD

**Issue by sriharirufus** [hoang-rio/vpngate-connector#1]
i'm looking forward to UDP works in your app, and i can't find a way to open your google service json as it's encrypted. Please help me how to open this file

thank you

**Comment by hoang-rio** [comment]
google-service.json is my private file. For UDP server list you can use python script at https://github.com/hoang-rio/vpn-gate-openvpn-udp to make csv list with udp server yourself.
