### ISSUE TITLE
App crashes when vpn is running and app is opened 

### ISSUE THREAD

**Issue by arjunshah17** [hoang-rio/vpngate-connector#2]
connecting vpn ,when app is in background and again if app is opened through notification or recent apps,it freeze and crashes

**Comment by hoang-rio** [comment]
Please provide more information:
1. OS Version
2. Free RAM
3. Device vendor
4. Device Model

**Comment by arjunshah17** [comment]
Os:Android 10
Free ram:not noted at that time
Vendor:Samsung m30s 
Happen some time

**Comment by hoang-rio** [comment]
Please retry with lastest code on master branch. If you got reportSize crash log it's know bug of samsung device. No solution to fix it at this moment. If another crash log it might resolved with lastest code on master branch.
